export { default as BoldIcon } from "./bold.svg";
export { default as H1Icon } from "./h1.svg";
export { default as H2Icon } from "./h2.svg";
export { default as H3Icon } from "./h3.svg";
export { default as H4Icon } from "./h4.svg";
export { default as ImageIcon } from "./image.svg";
export { default as ItalicIcon } from "./italic.svg";
export { default as QuotesIcon } from "./quotes.svg";
export { default as StrikeIcon } from "./strike.svg";
